runtime: python37
default_expiration: 0s
automatic_scaling:
  min_instances: 0
  min_idle_instances: 0


handlers:
- url: /api/.*
  script: auto

- url: /static
  static_dir: static/

- url: /
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

- url: /css
  static_dir: frontend/dist/css
  mime_type: text/css
  expiration: 1d

- url: /js
  static_dir: frontend/dist/js
  expiration: 1d

- url: /img
  static_dir: frontend/dist/img
  expiration: 1d

- url: /icons
  static_dir: frontend/dist/icons
  expiration: 1d

- url: /favicon.ico
  static_files: frontend/dist/favicon.ico
  upload: frontend/dist/favicon.ico

- url: /manifest.json
  static_files: frontend/dist/manifest.json
  upload: frontend/dist/manifest.json

- url: /browserconfig.xml
  static_files: frontend/dist/browserconfig.xml
  upload: frontend/dist/browserconfig.xml

- url: /log
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

- url: /map
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

- url: /graph
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

- url: /comparison
  static_files: frontend/dist/index.html
  upload: frontend/dist/index.html

