# Generated by Django 3.0.5 on 2020-04-03 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('county_short_name', models.CharField(max_length=2)),
                ('county_code', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('cases', models.IntegerField()),
                ('tests', models.IntegerField(blank=True, null=True)),
                ('tested_people', models.IntegerField(blank=True, null=True)),
                ('dead', models.IntegerField(blank=True, null=True)),
                ('icu', models.IntegerField(blank=True, null=True)),
                ('critical', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('time_updated', models.DateTimeField(auto_now=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
