# Generated by Django 3.0.5 on 2020-04-04 15:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('romania', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romania.County')),
            ],
        ),
        migrations.RenameModel(
            old_name='Data', new_name='DailyReport'
        ),
        migrations.AddField(
            model_name='dailyreport',
            name='county_data',
            field=models.ManyToManyField(through='romania.CountyData', to='romania.County'),
        ),
        migrations.AddField(
            model_name='countydata',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='romania.DailyReport'),
        ),
    ]
