# Generated by Django 3.0.5 on 2020-04-05 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('romania', '0002_auto_20200404_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='countydata',
            name='cases',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='cases',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
